.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .github/azure-pipelines/templates/build.yaml, README.md, package-lock.json, package.json, test/integration/WireMock.spec.ts
Update pipeline to use package-lock and run integration tests
Documentation updated (`api.md`,`read.me`, etc)
=> update pipeline yaml

package-lock.json, src/WireMock.ts, test/integration/WireMock.spec.ts, test/unit/WireMock.spec.ts
add more methods to get info about the requests made
- add `getAllRequests` fn
- add `getUnmatchedRequests` fn
- update some names to be more clear
- add tests
=> add request/mapping features

CHANGELOG.md, package.json
prepare for release
- update version
- update changelog
=> version update: 1.2.0

CHANGELOG.md, package.json
Release new version
- update `package.json`
- update `CHANGELOG`
=> release: 1.3.0

.npmignore, src/IWireMockTypes.ts, src/WireMock.ts
do not pack example app. improve type for `method`
- unless properly configured, a dependent service might end up running test for example app
- improve typings
=> update package files, types

CHANGELOG.md, package.json
release next version
- update changelog
- update version
=> release: 1.3.1

package-lock.json, package.json
Version bump
Prepare new version for `WireMockAPI`
=> release: 1.5.0

README.md, package.json
Update references to `master` in the README.
The package version is bumped up so that after merge, we can publish latest (just a docs update).
=> Update readme branch links

package-lock.json, package.json
Patch release
Update patch version
=> release: 1.5.2

package-lock.json, package.json
=> release: 1.6.0

package-lock.json, package.json
major release bump
major release as `node-fetch` types were used for function responses which has since been changed to use axios response
=> release 2.0.0

package-lock.json, package.json
Release update
Update minor version
=> release: 2.1.0

package-lock.json, package.json
Minor version bump
update for release
=> release: 2.2.0

package-lock.json, package.json, src/WireMock.ts
Update return type of a function
- `getAllMappings` returns an array of mappings
e.g.
```
[
{
id: '7b0d44c6-5ea0-4624-80f1-30e329ebca40',
request: { urlPattern: '.*', method: 'ANY' },
response: { status: 200 },
uuid: '7b0d44c6-5ea0-4624-80f1-30e329ebca40',
priority: 3
}
]
```
=> release 2.2.1 + update return type

README.md, examples/express-app/test/integration/server.spec.ts, package-lock.json, package.json, tsconfig.json
Update dependencies, README
- Update README
- Update dependencies
- Update `tssconfig`
=> Update dependencies, README

CHANGELOG.md, package-lock.json, package.json
Create new release
Update changelog
=> release: 3.0.0

examples/open-source-101/snippets/query-param-eq-match.ts
Fix example to not equality check on the query parameters as part of URL
=> docs: fix oss101 example

CHANGELOG.md, package-lock.json, package.json
Create new release: `3.0.1`
n/a
=> release: 3.0.1

CHANGELOG.md, package-lock.json, package.json
=> release: 3.0.2

.github/workflows/codeql-analysis.yml
=> chore: create codeql-analysis.yml

CHANGELOG.md, package-lock.json, package.json
Version bump
update changelog and version
=> release: 3.1.0

CHANGELOG.md, package-lock.json, package.json
=> release: 3.1.1

tsconfig.eslint.json
use single tsconfig for eslint as well as the build process, just with different directories included
n/a
=> chore: fix eslint tsconfig

docs/examples/README.md
Fix method name in docs/examples/README.md
N/A
=> Fix method name in docs/examples/README.md

package-lock.json, package.json, src/types/externalTypes.ts
=> feat: add xml match type

.devcontainer/devcontainer.json, README.md
add devcontainer setup for codespaces or quick local dev setup
n/a
=> chore: add devcontainer setup

.github/workflows/version-bump.yml
=> fix: version bump action

package-lock.json, package.json
=> chore: release 3.3.2

.github/azure-pipelines/ci-build.yaml, .github/azure-pipelines/publish.yaml
make azure pipeline node version match project version
=> chore: update azure pipeline node version

README.md, docs/examples/README.md, examples/express-app/README.md, examples/open-source-101/README.md, scripts/setup.sh, src/RequestModel.ts, src/types/IWireMockFeatures.ts, src/types/IWireMockRequest.ts, test/integration/WireMock.spec.ts, test/unit/RequestModel.spec.ts
Add support for form parameters and ignore JSON order
resolves #546 
https://wiremock.org/docs/request-matching/#less-strict-matching
https://wiremock.org/docs/request-matching/#request-with-form-parameters
=> feat: form parameters and less strict matching

package-lock.json, package.json
=> chore: release 3.4.0

package-lock.json, package.json
minor version update for response templating support
n/a
=> chore: release 3.5.0

docs/examples/README.md, package-lock.json, package.json, src/WireMock.ts, src/types/IWireMockRequest.ts, src/types/internalTypes.ts, test/integration/WireMock.spec.ts, test/unit/WireMock.spec.ts
Add functionality to find and remove stubs by metadata
solves #696
=> feat: stub metadata

package-lock.json, package.json
new version due to dependency updates
n/a
=> chore: v4.1.1

package-lock.json, package.json
Patch version update
New release
=> chore: v4.1.2
